apiVersion: apps/v1
kind: Deployment
metadata:
  name: redbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redbook
  template:
    metadata:
      labels:
        app: redbook
    spec:
      containers:
        - name: redbook
          image: redbook:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://192.168.5.13:3306/redbook?allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: chuwa
            - name: SPRING_DATASOURCE_PASSWORD
              value: chuwa

---
apiVersion: v1
kind: Service
metadata:
  name: redbook-service
spec:
  type: NodePort
  selector:
    app: redbook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080