# R2DBC datasource configuration
spring.r2dbc.url=r2dbc:mysql://192.168.5.13:3306/redbook?allowPublicKeyRetrieval=true&useSSL=false
spring.r2dbc.username=chuwa
spring.r2dbc.password=chuwa

# Initialize schema/data.sql at startup (optional)
spring.sql.init.mode=always
spring.sql.init.platform=mysql